alg: ppo
policy: MlpPolicy
learning_rate: 3e-4
n_steps: 256 # number of steps for each environment
batch_size: 256 # should be a factor of n_steps * n_envs
n_epochs: 5
gamma: 0.997
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: null
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: false
sde_sample_freq: -1
target_kl: null
stats_window_size: 100
tensorboard_log: "./"
verbose: 1