hydra.output_subdir: null
learn:
  total_timesteps: 50000000
seed: 0
log_dir: '/data/air_hockey/amir/logs'
log_interval: 10 # log statistics every n episodes
exp_name: ALP-GMM_for_Airhockey
nb_reward_coeff: 3 # havaset be env ham bashe onja ham hast in
parallel: 20
epochs: 8000
max_episode_len: 100
steps_per_epoch: 2000  
nb_test_episodes: 50
env: air_hockey
use_teacher: True
defaults:
  - callbacks:
      - custom_eval
      - checkpoint
      - info_log
      - teacher
  - algorithm:
      sac
  - environment:
      air_hockey
  - teacher:
      ALP-GMM

